/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BookReturnRouteImport } from './routes/book.return'
import { Route as BookCheckoutRouteImport } from './routes/book.checkout'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminArtistsRouteImport } from './routes/admin.artists'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const BookReturnRoute = BookReturnRouteImport.update({
  id: '/book/return',
  path: '/book/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCheckoutRoute = BookCheckoutRouteImport.update({
  id: '/book/checkout',
  path: '/book/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/book/checkout': typeof BookCheckoutRoute
  '/book/return': typeof BookReturnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/book/checkout': typeof BookCheckoutRoute
  '/book/return': typeof BookReturnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/book/checkout': typeof BookCheckoutRoute
  '/book/return': typeof BookReturnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/merch'
    | '/sitemap.xml'
    | '/admin/artists'
    | '/admin/bookings'
    | '/admin/gallery'
    | '/admin/orders'
    | '/admin/settings'
    | '/artists/$slug'
    | '/book/checkout'
    | '/book/return'
    | '/checkout/return'
    | '/admin/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/merch'
    | '/sitemap.xml'
    | '/admin/artists'
    | '/admin/bookings'
    | '/admin/gallery'
    | '/admin/orders'
    | '/admin/settings'
    | '/artists/$slug'
    | '/book/checkout'
    | '/book/return'
    | '/checkout/return'
    | '/admin'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/merch'
    | '/sitemap.xml'
    | '/admin/artists'
    | '/admin/bookings'
    | '/admin/gallery'
    | '/admin/orders'
    | '/admin/settings'
    | '/artists/$slug'
    | '/book/checkout'
    | '/book/return'
    | '/checkout/return'
    | '/admin/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  BookCheckoutRoute: typeof BookCheckoutRoute
  BookReturnRoute: typeof BookReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/book/return': {
      id: '/book/return'
      path: '/book/return'
      fullPath: '/book/return'
      preLoaderRoute: typeof BookReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/checkout': {
      id: '/book/checkout'
      path: '/book/checkout'
      fullPath: '/book/checkout'
      preLoaderRoute: typeof BookCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminArtistsRoute: typeof AdminArtistsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtistsRoute: AdminArtistsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  BookCheckoutRoute: BookCheckoutRoute,
  BookReturnRoute: BookReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
